#!/bin/bash
# script for publishing to Github pages. Based on the Hugo
# documentation.

# copy static files
PDFS=./static/pdf/
cp ~/doc/cv/cv.pdf $PDFS/cv.pdf
cp ~/research/consistent-local-continuous/doc/consistent-local-continuous.pdf $PDFS

# erases the contents of the target directory without asking, then
# pushes that as a git repo
PUB=./public
mv $PUB/CNAME .
rm -R ./$PUB/*
mv CNAME $PUB
hugo
cd $PUB
git add --all && git commit -m "Publishing to gh-pages."
git push origin master
