#!/bin/bash
WEAVE=$HOME/.julia/v0.5/Weave/bin/weave.jl
WEAVEFLAGS="--doctype hugo --out_path ../content/post --fig_path figures --plotlib Plots"

if [ $# -ne 1 ]
  then
    echo """
Use as
  jweave filename.jmd
"""
fi

$WEAVE $WEAVEFLAGS $1
